SELECT
  date,
  company,
  close,
  AVG(close) OVER (PARTITION BY company ORDER BY date ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sma20,
  AVG(close) OVER (PARTITION BY company ORDER BY date ROWS BETWEEN 49 PRECEDING AND CURRENT ROW) AS sma50,
  AVG(close) OVER (PARTITION BY company ORDER BY date ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS sma200
FROM public.quotes;
